version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Running npm install
      - npm install

  build:
    commands:
      - echo Building project on `date`
      - echo Execute unit tests
      - npm run test
      - npm run compile

  post_build:
    commands:
      - echo Build completed on `date`
